---
- name: Setup data disk
  hosts: core
  become: true
  tasks:
    - name: Ensure partition is formatted
      filesystem:
        fstype: ext4
        dev: /dev/nvme1n1
    - name: Ensure file systems is mounted
      mount:
        fstype: ext4
        src: /dev/nvme1n1
        path: /data
        state: mounted
    - name: Create 2GB swap
      command: fallocate -l 2G /tmp/swapfile
      args:
        creates: /tmp/swapfile
    - name: Set swap permissions
      command: chmod 600 /tmp/swapfile
    - name: Set swap file
      command: mkswap /tmp/swapfile
    - name: Enable swap
      command: swapon /tmp/swapfile