---
- name: Setup db
  hosts: core
  become: yes
  tasks:
    - name: Setup postgres
      docker_container:
        name: postgres
        image: postgres:15.4
        volumes:
          - /data/postgres:/var/lib/postgresql/data
        restart_policy: always
        restart: yes
        env:
          POSTGRES_USER: "{{ postgres_user }}"
          POSTGRES_PASSWORD: "{{ postgres_password }}"
          POSTGRES_DB: "bitcoin-coverage"
