---
- name: Setup bitcoin-coverage backend
  hosts: core
  become: yes
  tasks:
    - name: Setup backend
      docker_container:
        name: core
        image: aureleoules/bitcoin-coverage-core:latest
        restart_policy: always
        restart: yes
        pull: true
        env:
          DB_HOST: "127.0.0.1"
          DB_USER: "{{ postgres_user }}"
          DB_PASSWORD: "{{ postgres_password }}"
          DB_NAME: "bitcoin-coverage"
          DB_PORT: "5432"
          GITHUB_ACCESS_TOKEN: "{{ github_access_token }}"
          SESSION_SECRET: "{{ session_secret }}"
          GH_OAUTH_SECRET: "{{ gh_oauth_secret }}"
          GH_OAUTH_REDIRECT_URL: "{{ gh_oauth_redirect_url }}"
        network_mode: host
    - name: Prune docker system
      docker_prune:
        images: yes
        containers: yes
        volumes: yes
        networks: yes