---
- name: Setup bitcoin-coverage backend
  hosts: core
  become: yes
  tasks:
    - name: Setup backend
      docker_container:
        name: core
        image: aureleoules/bitcoin-coverage-core:latest
        restart_policy: always
        restart: yes
        pull: true
        env:
          DB_HOST: "postgres"
          DB_USER: "{{ postgres_user }}"
          DB_PASSWORD: "{{ postgres_password }}"
          DB_NAME: "bitcoin-coverage"
          DB_PORT: "5432"
          GITHUB_ACCESS_TOKEN: "{{ github_access_token }}"
        network_mode: host
