---
- name: Setup bitcoin-coverage backend
  hosts: core
  become: yes
  tasks:
    - name: Create config folder
      file:
        path: /etc/core
        state: directory
    - name: Create config file
      template:
        src: ../config/core/config.yml.j2
        dest: /etc/core/config.yml
    - name: Setup backend
      docker_container:
        name: core
        image: aureleoules/bitcoin-coverage-core:latest
        restart_policy: always
        restart: yes
        pull: true
        network_mode: host
        volumes:
          - /etc/core/config.yml:/app/config.yml
        env:
          AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
          AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"