---
- name: Setup bitcoin-coverage frontend
  hosts: core
  become: yes
  tasks:
    - name: Setup frontend
      docker_container:
        name: frontend
        image: aureleoules/bitcoin-coverage-ui:latest
        restart_policy: always
        restart: yes
        pull: true
        network_mode: host
        env:
          PUBLIC_ENDPOINT: "/api"
          PUBLIC_REDIRECT_URL: "https://{{ domain_name }}/callback"
          PUBLIC_CLIENT_ID: "{{ gh_oauth_client_id }}"
    - name: Prune docker system
      docker_prune:
        images: yes
        containers: yes
        volumes: yes
        networks: yes