---
- name: Install and configure Nginx
  hosts: core
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name:
          - nginx
          - certbot
          - python3-certbot-nginx
        state: present
    - name: Create nginx config file
      template:
        src: ../config/nginx/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: 
        - restart nginx
    - name: Certbot nginx
      shell: certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos --email {{ email }}
      notify: 
        - restart nginx
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
