---
- name: Setup db
  hosts: db
  become: yes
  tasks:
    - name: Setup postgres
      docker_container:
        name: postgres
        image: postgres:15.4
        volumes:
          - /data/postgres:/var/lib/postgresql/data
        restart_policy: always
        restart: yes
        env:
          POSTGRES_USER: "{{ lookup('ansible.builtin.env', 'DB_USER') }}"
          POSTGRES_PASSWORD: "{{ lookup('ansible.builtin.env', 'DB_PASSWORD') }}"
          POSTGRES_DB: "corecheck"
        network_mode: host